
development:
  adapter: postgresql
  encoding: unicode
  database: girl_on_fire_development
  pool: 5
  username: DtotheFP
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: girl_on_fire_test
  pool: 5
  username: DtotheFP
  password:


